data:
  types_first: true
  dataset_type: "raw"
  add_timing: true
  add_snapping: true
  add_timing_points: true
  add_hitsounds: true
  add_distances: true
  add_positions: true
  add_kiai: true
  add_sv: true
  position_precision: 32
  position_split_axes: false
  position_range: [-256, 768, -256, 640]
  gamemodes: [0]
  ms_per_seq: 32768

optim: # Optimizer settings
  name: adamw
  base_lr: 1e-4 # Should be scaled with the number of devices present
  batch_size: 64 # This is the batch size per GPU
  total_steps: 65536
  warmup_steps: 10000
  lr_scheduler: cosine
  weight_decay: 0.0
  grad_clip: 1.0
  grad_acc: 4
  final_cosine: 1e-5

dataloader:
  num_workers: 8

eval: # Evaluation settings
  #every_steps: 2000
  every_steps: 1000
  steps: 250

checkpoint: # Checkpoint settings
  every_steps: 4000
