data:
  types_first: true
  dataset_type: "raw"
  add_gamemode_token: false
  add_diff_token: false # Most "special" tokens are disabled
  add_style_token: false
  add_mapper_token: false
  add_year_token: false
  add_sv_special_token: false
  add_cs_token: true
  add_hitsounded_token: false
  add_song_length_token: false
  add_song_position_token: false
  add_descriptors: false
  add_sv: false
  add_timing_points: false
  add_empty_sequences: false
  class_dropout_prob: 0.0 # add_style_token is disabled anyway
  hitsound_dropout_prob: 0.0
  x_flip_prob: 0.0
  y_flip_prob: 0.0
  dt_augment_prob: 0.0
  position_precision: 4
  position_split_axes: true
  position_range: [-256, 768, -256, 640]
  gamemodes: [0]
  ms_per_seq: 32768

optim: # Optimizer settings
  name: adamw
  base_lr: 1e-4 # Should be scaled with the number of devices present
  batch_size: 64 # This is the batch size per GPU
  total_steps: 65536
  warmup_steps: 10000
  lr_scheduler: cosine
  weight_decay: 0.0
  grad_clip: 1.0
  grad_acc: 4
  final_cosine: 1e-5

dataloader:
  num_workers: 8

eval: # Evaluation settings
  #every_steps: 2000
  every_steps: 1000
  steps: 250

checkpoint: # Checkpoint settings
  every_steps: 4000
