defaults:
  - /osubert/base_train@_here_

precision: "bf16-mixed"
compile: false

data:
  dataset_type: "raw"
  train_dataset_path: ""
  test_dataset_path: ""
  train_dataset_start: 0
  train_dataset_end: 0
  test_dataset_start: 0
  test_dataset_end: 0
  add_gamemode_token: false
  add_diff_token: false # Most "special" tokens are disabled
  add_style_token: false
  add_mapper_token: false
  add_year_token: false
  add_sv_special_token: false
  add_cs_token: true
  add_hitsounded_token: false
  add_song_length_token: false
  add_song_position_token: false
  add_descriptors: false
  add_sv: false
  add_timing_points: false
  class_dropout_prob: 0.0 # add_style_token is disabled anyway
  hitsound_dropout_prob: 1.0
  x_flip_prob: 0.0
  y_flip_prob: 0.0
  gamemodes: [0]
  add_empty_sequences: false
  min_difficulty: 4.0
  #min_year: 2020
  add_timing: true
  dt_augment_prob: 0.0
  timing_random_offset: 0
  overlap_divisor: 2
  cycle_length: 1
  position_precision: 4
  position_split_axes: true

dataloader:
  num_workers: 8
