defaults:
  - /osubert/base_train@_here_

precision: "bf16-mixed"
compile: true

data:
  dataset_type: "mmrs"
  train_dataset_path: "E:\\osudataset\\data"
  test_dataset_path: "E:\\osudataset\\data"
  train_dataset_start: 0
  train_dataset_end: 31604
  test_dataset_start: 31604
  test_dataset_end: 31704
  add_gamemode_token: false
  add_diff_token: false     # Most "special" tokens are disabled
  add_style_token: false
  add_mapper_token: false
  add_year_token: false
  add_sv_special_token: false
  add_cs_token: true
  add_hitsounded_token: false
  add_song_length_token: true
  add_song_position_token: true
  add_descriptors: false
  add_sv: true
  class_dropout_prob: 0.0   # add_style_token is disabled anyway
  gamemodes: [0]
  add_empty_sequences: false
  add_timing: true
  dt_augment_prob: 0.0

optim:                  # Optimizer settings
  name: adamw
  base_lr: 1e-4         # Should be scaled with the number of devices present
  batch_size: 8         # This is the batch size per GPU
  total_steps: 65536
  warmup_steps: 10000
  lr_scheduler: cosine
  weight_decay: 0.0
  grad_clip: 1.0
  grad_acc: 4
  final_cosine: 1e-5

dataloader:
  num_workers: 4

eval:                   # Evaluation settings 
  #every_steps: 2000
  every_steps: 1000
  steps: 250

checkpoint:             # Checkpoint settings
  every_steps: 4000